"""
Planning session with Gemini 3 Pro
Identify all libraries, tools, and architecture needed for Offside Zero
"""

import google.generativeai as genai
import os
import json

# Configure
genai.configure(api_key=os.environ.get("GEMINI_API_KEY"))

PLANNING_PROMPT = """You are a senior AI/ML engineer and football technology expert. 
We are building "Offside Zero" for the Gemini 3 Hackathon (deadline: Feb 10, 2026).

## Project Goal
Build an AI-powered football officiating assistant that:
1. Analyzes RECORDED match footage (prototype stage)
2. Detects OFFSIDE violations (attacker beyond last defender when ball is played)
3. Detects HANDBALL violations (illegal arm/hand contact with ball)
4. Outputs:
   - Slow-motion annotated replay with VAR-style overlays
   - Live decision dashboard for referees/viewers
   - Explainable decisions with confidence scores

## Constraints
- MUST use Gemini 3 API as the ONLY AI engine (hackathon rule)
- Must NOT be a simple prompt wrapper, basic RAG, or generic chatbot
- Must demonstrate spatial-temporal reasoning
- Need a working demo + 3-minute video
- Team: solo developer, 3 days remaining

## Current Stack
- Python (main backend)
- OpenCV for video processing
- Gemini 3 API for multimodal vision + reasoning

## Your Task
Provide a comprehensive technical plan covering:

1. **Architecture Overview**
   - System components and data flow
   - How Gemini 3 fits in (specific API features to use)

2. **Required Libraries & Tools**
   - Python packages (with versions)
   - Frontend framework for dashboard
   - Video processing tools
   - Any cloud/deployment needs

3. **Gemini 3 API Strategy**
   - Which model variant (Flash vs Pro vs Ultra)
   - Multimodal input handling (video frames)
   - Structured output for reliable parsing
   - Tool/function calling for overlay generation
   - Context window considerations for multi-frame analysis

4. **Computer Vision Approach**
   - Player detection and tracking
   - Ball detection
   - Pitch line detection for calibration
   - Offside line calculation algorithm
   - How to combine CV with Gemini reasoning

5. **Dashboard Design**
   - Real-time updates
   - Decision display
   - Replay viewer with annotations
   - Tech stack recommendation

6. **Demo Video Script**
   - Key scenes to show
   - How to demonstrate the AI reasoning
   - Estimated recording time

7. **Risk Mitigation**
   - What could go wrong in 3 days
   - Fallback approaches
   - MVP vs nice-to-have features

8. **Suggested File/Folder Structure**
   - Clean project layout for submission

Be specific, actionable, and prioritize what can realistically be achieved in 3 days by one developer.
Output as structured markdown.
"""

def main():
    print("🧠 Consulting Gemini 3 Pro for project planning...\n")
    
    model = genai.GenerativeModel("gemini-2.0-pro")
    
    response = model.generate_content(PLANNING_PROMPT)
    
    print("=" * 80)
    print("OFFSIDE ZERO - TECHNICAL PLANNING DOCUMENT")
    print("=" * 80)
    print()
    print(response.text)
    print()
    print("=" * 80)
    
    # Save to file
    with open("PLANNING.md", "w", encoding="utf-8") as f:
        f.write("# Offside Zero - Technical Planning Document\n\n")
        f.write("*Generated by Gemini 3 Pro*\n\n")
        f.write(response.text)
    
    print("\n📄 Saved to PLANNING.md")

if __name__ == "__main__":
    main()
